### PR TITLE
Make `session` required on `AuthenticationResponse`

### PR DESCRIPTION
**Pull request by maxdeviant**
## Description

This PR fixes a bug in the `AuthenticationResponse` type where the `session` field was marked as possibly being `undefined`.

The `session` will always be present on the `AuthenticationResponse`.

## Documentation

Does this require changes to the WorkOS Docs? E.g. the [API Reference](https://workos.com/docs/reference) or code snippets need updates.

```
[ ] Yes
```

If yes, link a related docs PR and add a docs maintainer as a reviewer. Their approval is required.

### CODE REVIEW

**Comment by willmanduffy** [comment]
In one case it appears to be marked as optional in the Docs. Is this where this came from? 

CleanShot 2023-08-09 at 13 41 35@2x

**Comment by maxdeviant** [comment]
> In one case it appears to be marked as optional in the Docs. Is this where this came from?
> 
> CleanShot 2023-08-09 at 13 41 35@2x

It was optional at one point (contingent on the value of `start_session`).

But those docs are out of date now, since `start_session` has been removed and we now always return the `session`.

**Comment by maxdeviant** [comment]
@oliverzheng Can you confirm the above? ☝🏻

**Comment by oliverzheng** [comment]
Can confirm. The doc is indeed out of date. Instead of removing the `start_session` param, the `sessions/token` endpoint now supports password auth and has obviated the `sessions/authentications` endpoint which supports the `start_session` param. The SDK has already been updated to use the new endpoint; the docs should be updated to reflect the new endpoint as well and the old endpoint should be removed entirely.

**Pull request merged**
