### PR TITLE
Merge main into v3.0.0

### PR DESCRIPTION
**Pull request by cmatheson**
## Description

Just getting the v3.0.0 branch current before tackling the items listed in https://www.notion.so/workos/Features-for-the-Next-Major-SDK-Release-4a425188c6b94d46a728e42abc509a62#c2e47b7921e14cc4adf649158c287f56.

## Documentation

Does this require changes to the WorkOS Docs? E.g. the [API Reference](https://workos.com/docs/reference) or code snippets need updates.

```
[ ] Yes
```

If yes, link a related docs PR and add a docs maintainer as a reviewer. Their approval is required.

### CODE REVIEW

**Comment by maxdeviant** [comment]
> Just getting the v3.0.0 branch current

Is the "v3.0.0 branch" `main` in this case?

The PR title is a little confusing, since we're merging this PR into `main`.

**Comment by cmatheson** [comment]
> The PR title is a little confusing, since we're merging this PR into main.

Ohh, it should have been `v3.0.0` (I was hoping `gh` would use my tracking branch as the branch to merge into, but it needed an edit).

**Comment by maxdeviant** [comment]
> > The PR title is a little confusing, since we're merging this PR into main.
> 
> Ohh, it should have been `v3.0.0` (I was hoping `gh` would use my tracking branch as the branch to merge into, but it needed an edit).

Seems like we should just use `main` for the next major version release (v3) instead of creating a new branch to track it.

And then we just keep the `v2.x` around if we need to release new `v2.x.x` versions in the meantime.

**Comment by cmatheson** [comment]
> Seems like we should just use main for the next major version release (v3) instead of creating a new branch to track it.

> And then we just keep the v2.x around if we need to release new v2.x.x versions in the meantime.

I like that idea better :+1:.

**Pull request closed without merging**
