### PR TITLE
Trigger release action for pre-releases

### PR DESCRIPTION
**Pull request by amadeo-workos**
## Description
@PaulAsjes @mattgd 

## Documentation

Does this require changes to the WorkOS Docs? E.g. the [API Reference](https://workos.com/docs/reference) or code snippets need updates.

```
[ ] Yes
```

If yes, link a related docs PR and add a docs maintainer as a reviewer. Their approval is required.

### CODE REVIEW

**Comment by jasonroelofs** [comment]
This will publish any pre-release/beta version as the `latest` tag, is the plan here to then remember to run `fix-latest`? Or we can make this deploy a little smarter.

**Comment by jasonroelofs** [comment]
E.g. what we do with `authkit-nextjs` https://github.com/workos/authkit-nextjs/blob/main/.github/workflows/release.yml

**Review by PaulAsjes — APPROVED** [review]

**Comment by PaulAsjes** [comment]
Oops hit approve too soon, we should address @jasonroelofs's comments about making deploys smarter.

**Comment by amadeo-workos** [comment]
@jasonroelofs yeah, good call... Let me know what you think of the fix now!

**Review by jasonroelofs — APPROVED** [review]

**Pull request merged**
